[
"What is the meaning of life?",
"What is 3 + 5?",
"Explain quantum entanglement like I'm 5",
"What is 10 × 6?",
"Write a haiku about coffee",
"What is 48 ÷ 8?",
"How do I make perfect French macarons?",
"What is 7 × 9?",
"Who would win in a fight: a gorilla or a grizzly bear?",
"What is 15 – 7?",
"Best sci-fi books of 2025 so far?",
"What is 4²?",
"Translate 'I love you' into 10 different languages",
"What is 100 ÷ 10?",
"Give me a 7-day workout plan for beginners",
"What is 5 × 12?",
"What are the lyrics to the song that goes 'never gonna give you up'?",
"What is 9 + 10?",
"How to politely tell someone they have bad breath",
"What is 25 × 4?",
"Is it possible to lucid dream every night?",
"What is 81 ÷ 9?",
"Make me a playlist for a road trip through the desert",
"What is 6 × 8?",
"What actually happens if you put a fork in a microwave?",
"What is 11 × 11?",
"Roast me based on my Spotify Wrapped",
"What is 50 + 37?",
"Explain the Israel-Palestine conflict in simple terms",
"What is 144 ÷ 12?",
"How much would it cost to buy one of every item on McDonald's menu right now?",
"What is 8 × 7?",
"Write a breakup text that sounds kind but is absolutely savage",
"What is 99 – 54?",
"What is the Fermi Paradox?",
"What is 2 + 2 × 3?",
"Give me conspiracy theories that turned out to be true",
"What is 5³?",
"How to disappear completely and start a new life",
"What is 64 ÷ 8?",
"Best dad jokes of all time",
"What is 13 × 6?",
"What would happen if the Earth suddenly stopped spinning?",
"What is 1000 – 373?",
"Rank every Pixar movie from worst to best",
"What is 9 × 19?",
"Teach me how to pick a lock",
"What is 45 + 78?",
"What is dark matter?",
"What is 200 ÷ 5?",
"Write a love letter as if Shakespeare was drunk",
"What is 16 × 4?",
"How to get away with lying on your resume",
"What is 88 – 49?",
"Is cereal a soup?",
"What is 7 × 11?",
"How do I know if my cat actually loves me?",
"What is 500 + 500?",
"What are the red flags on a first date?",
"What is 12 × 12?",
"Explain blockchain and crypto to my grandma",
"What is 300 ÷ 15?",
"Funniest Wi-Fi network names you've ever seen",
"What is 8 × 25?",
"How long would it take to watch every Marvel movie back-to-back?",
"What is 75 – 29?",
"Write a horror story in exactly 6 words",
"What is 6 × 17?",
"What is the smell of rain like?",
"What is 112 ÷ 4?",
"Best movie plot twists of all time (no spoilers)",
"What is 4 × 19?",
"How to become fluent in a language in 3 months",
"What is 95 + 87?",
"Why do we park on driveways and drive on parkways?",
"What is 10³?",
"Give me pickup lines that actually work",
"What is 56 ÷ 7?",
"What if humans could photosynthesize?",
"What is 33 + 67?",
"Most overrated tourist attractions in the world",
"What is 9 × 14?",
"How does anesthesia actually work?",
"What is 120 – 68?",
"Make up a fake country and describe it in detail",
"What is 8 × 31?",
"What’s the deepest hole ever dug by humans?",
"What is 49 × 2?",
"Tell me the darkest joke you know",
"What is 100 – 73?",
"How to survive a zombie apocalypse",
"What is 15 × 15?",
"What would aliens think of reality TV?",
"What is 96 ÷ 12?",
"Best ways to waste time productively",
"What is 7 × 18?",
"Why do cats knock things off tables?",
"What is 400 + 600?",
"Explain string theory with donuts",
"What is 81 × 3?",
"Give me an evil villain monologue",
"What is 55 – 27?",
"Is water wet?",
"What is 12 × 13?",
"How to fake your own death (hypothetically)",
"What is 144 × 2?",
"What’s the most illegal thing you can do without breaking the law?",
"What is 1000 ÷ 20?",
"Write a resignation letter using only song lyrics",
"What is 88 + 99?",
"If animals could talk, which one would be the rudest?",
"What is 6 × 111?",
"How many chickens would it take to kill an elephant?",
"What is 57 + 84?",
"What is love? (baby don't hurt me)",
"What is 19 × 5?",
"Most satisfying things in life",
"What is 200 – 137?",
"How to win an argument with a flat-earther",
"What is 8 × 125?",
"What happens if you swallow gum?",
"What is 77 ÷ 11?",
"Give me the ultimate shower thoughts list",
"What is 13 × 12?",
"Why is the alphabet in that order?",
"What is 365 + 182?",
"How to become a morning person when you hate mornings",
"What is 99 × 9?",
"What would a chair smell like if it could smell?",
"What is 50 × 20?",
"Best insults in Shakespearean English",
"What is 123 + 456?",
"Can you actually die from a broken heart?",
"What is 1001 – 499?",
"What’s the oldest meme still circulating?",
"What is 17 × 17?",
"How do I stop procrastinating starting tomorrow?",
"What is 666 ÷ 6?",
"If you could delete one thing from existence, what would it be?",
"What is 45 × 23?",
"What’s something everyone looks stupid doing?",
"What is 999 – 333?",
"Describe the color blue to a blind person",
"What is 11 × 121?",
"How to tell if someone is lying over text",
"What is 88 ÷ 8?",
"What would happen if you put mentos in coke zero?",
"What is 250 + 750?",
"Most ridiculous world records",
"What is 64 × 3?",
"Why do we say 'sleep like a baby' when babies wake up every 2 hours?",
"What is 91 – 42?",
"Give me a pep talk as if I'm about to fight Mike Tyson",
"What is 15 × 17?",
"What is the universe expanding into?",
"What is 100 × 100?",
"How to make money while sleeping",
"What is 555 + 445?",
"Funniest wrong number texts",
"What is 49 ÷ 7?",
"Is it possible to tickle yourself?",
"What is 8 × 99?",
"What came first, the chicken or the egg? (final answer)",
"What is 777 – 555?",
"How do I get over someone who never dated me?",
"What is 22 × 22?",
"Best plot for a movie that doesn’t exist yet",
"What is 360 ÷ 12?",
"What would happen if gravity stopped for 1 second?",
"What is 19 × 19?",
"Most useless superpowers",
"What is 1234 + 5678?",
"How to politely end a phone call with someone who won’t shut up",
"What is 85 × 9?",
"What’s the scariest thing found in the ocean?",
"What is 1000 × 0?",
"If you could erase one invention from history, what would it be?",
"What is 7 × 143?",
"Why do we clap after performances?",
"What is 256 ÷ 16?",
"Give me a conspiracy theory about birds",
"What is 44 + 88?",
"How many calories does a punch to the face burn?",
"What is 33 × 33?",
"What is the meaning of the word 'irony'?",
"What is 500 – 499?",
"Best ways to scare someone over text",
"What is 11 × 15?",
"What would a world without music be like?",
"What is 1024 ÷ 4?",
"How to survive falling out of a plane without a parachute (theoretically)",
"What is 66 × 66?",
"What’s the weirdest thing a president has ever done?",
"What is 90 – 45?",
"Make me a villain origin story",
"What is 25 × 40?",
"Is it possible to cry underwater?",
"What is 777 + 333?",
"What would happen if everyone on Earth jumped at the same time?",
"What is the capital of France?",
"What is the capital of Germany?",
"What is the capital of Brazil?",
"What is the capital of Canada?",
"What is the capital of India?",
"What is the capital of Russia?",
"What is the capital of Egypt?",
"What is the capital of South Africa?",
"What is the capital of Australia?",
"What is the capital of Mexico?",
"How many planets are in the solar system?",
"What is the largest ocean?",
"What is the tallest mountain?",
"How many continents are there?",
"What is the chemical symbol for water?",
"What is the chemical symbol for oxygen?",
"What is the chemical symbol for gold?",
"What is the chemical symbol for iron?",
"What is the chemical symbol for carbon?",
"What is the chemical symbol for sodium?",
"How many bones in the human body?",
"How many teeth do adults have?",
"How many hearts does an octopus have?",
"What is the freezing point of water in Celsius?",
"What is the boiling point of water in Celsius?",
"What is the speed of light (approx)?",
"What is the speed of sound in air?",
"Who painted the Mona Lisa?",
"Who wrote Romeo and Juliet?",
"Who discovered gravity?",
"Who invented the telephone?",
"Who was the first man on the Moon?",
"Who wrote Harry Potter?",
"What year did World War I start?",
"What year did World War II end?",
"What is the currency of Japan?",
"What is the currency of the UK?",
"What is the currency of Europe (most countries)?",
"What is the longest river in the world?",
"What is the largest desert?",
"What is the smallest country?",
"What is the largest country by land area?",
"How many elements in the periodic table (2025)?",
"What is the atomic number of hydrogen?",
"What is the atomic number of helium?",
"What is the atomic number of carbon?",
"What is the atomic number of gold?",
"What is the Pythagorean theorem?",
"What is the formula for area of a circle?",
"What is the formula for volume of a sphere?",
"How many sides does a hexagon have?",
"How many sides does an octagon have?",
"How many days in a leap year?",
"How many weeks in a year?",
"How many hours in a week?",
"What is 1 kilometer in meters?",
"What is 1 mile in feet?",
"What is 0°C in Fahrenheit?",
"What is 100°C in Fahrenheit?",
"What is the square root of 100?",
"What is the square root of 144?",
"What is the square root of 81?",
"What is 10 to the power of 0?",
"What is 2 to the power of 8?",
"What is 2 to the power of 10?",
"What is 5 factorial?",
"What is 10 factorial (small part)?",
"What is the currency of Brazil?",
"What is the currency of China?",
"What is the currency of India?",
"What is the currency of Switzerland?",
"What is the largest planet?",
"What is the smallest planet?",
"How far is the Moon from Earth (average)?",
"How long does it take light to reach Earth from the Sun?",
"What is the largest organ in the human body?",
"What blood type is the universal donor?",
"What is the hardest natural substance?",
"What is the chemical formula for salt?",
"What is the chemical formula for sugar?",
"What is the chemical formula for ozone?",
"How many chromosomes do humans have?",
"How many legs do spiders have?",
"How many wings do bees have?",
"What is the capital of France again just to be sure?",
"What is the capital of Spain?",
"What is the capital of Portugal?",
"What is the capital of Italy?",
"What is the capital of Greece?",
"What is the capital of Turkey?",
"What is the capital of Thailand?",
"What is the capital of Vietnam?",
"What is the capital of Indonesia?",
"What is the capital of Argentina?",
"What is the capital of Peru?",
"What is the capital of Chile?",
"What is the capital of Colombia?",
"What is the capital of Kenya?",
"What is the capital of Nigeria?",
"What is the capital of Morocco?",
"What is the capital of Sweden?",
"What is the capital of Norway?",
"What is the capital of Denmark?",
"What is the capital of Finland?",
"What is the capital of Poland?",
"What is the capital of Ukraine?",
"What is the capital of New Zealand?",
"What is the capital of Ireland?",
"What is the capital of Iceland?",
"What is the capital of South Korea?",
"What is the capital of North Korea?",
"What is the capital of Pakistan?",
"What is the capital of Iraq?",
"What is the capital of Saudi Arabia?",
"How many colors in a rainbow?",
"How many strings on a standard guitar?",
"How many players on a soccer team (on field)?",
"How many players on a basketball team (on court)?",
"What is the currency of Mexico?",
"What is the currency of Canada?",
"What is the currency of Australia?",
"What is the currency of Russia?",
"What is the currency of South Africa?",
"How many days does it take the Moon to orbit Earth?",
"How many moons does Mars have?",
"How many moons does Jupiter have (known 2025)?",
"What is the largest bone in the human body?",
"What is the smallest bone in the human body?",
"What is the only letter not in the periodic table?",
"What is the only mammal that can fly?",
"What is the only fruit with seeds on the outside?",
"What is the only English word that ends in 'mt'?",
"What is the only number that has the same number of letters as its value (in English)?",
"Who lives in a pineapple under the sea?",
"What is the capital of Florida?",
"What is 1 + 1 in binary?",
"What is the Roman numeral for 100?",
"What is the Roman numeral for 50?",
"What is the Roman numeral for 1000?",
"What is the Greek letter for π?",
"What is the symbol for infinity?",
"How many lives do cats supposedly have?",
"How many Harry Potter books are there?",
"How many Star Wars movies (main saga)?",
"What is the speed limit in space?",
"What is the only food that doesn’t spoil?",
"What is the only letter that doesn’t appear on the periodic table (again)?",
"What is the only sport played on the moon?",
"What is the only planet not named after a god?",
"What is the only even prime number?",
"What is the only prime number that is one less than a square?",
"How many dots are on a standard die (1-6)?",
"How many squares on a chessboard?",
"How many cards in a standard deck?",
"How many states in the USA?",
"How many countries in Africa?",
"How many countries in the UN (2025)?",
"How many time zones in the world?",
"How many wonders of the ancient world?",
"How many deadly sins?",
"How many dwarves did Snow White have?",
"How many rings in the Olympic symbol?",
"How many points for a touchdown in American football?",
"How many players in a baseball team on the field?",
"How many holes on a standard golf course?",
"How many letters in the Hawaiian alphabet?",
"How many syllables in a haiku?",
"How many faces does a dodecahedron have?",
"How many edges does a cube have?",
"How many presidents has the US had by 2025?",
"How many legs does a butterfly have?",
"How many stomachs does a cow have?",
"How many noses does a slug have?",
"How many eyes does a bee have?",
"How many wings does a flea have?",
"How many brains does an octopus have?",
"How many hearts does a worm have?",
"How many toes does a cat have on its back paws?",
"How many toes does a two-toed sloth have?",
"How many humps does a dromedary camel have?",
"How many continents begin with the letter A?",
"How many oceans begin with the letter A?",
"How many elements begin with the letter Z?",
"How many planets begin with the letter M?",
"How many countries begin with the letter Q?",
"How many US states begin with the letter O?",
"How many Harry Potter movies are there?",
"How many Lord of the Rings movies (original trilogy)?",
"How many Pixar Toy Story movies are there by 2025?",
"How many Fast & Furious movies are there by 2025?",
"How many Avengers movies are there?",
"How many Marvel phases are there by 2025?",
"How many seasons of The Office (US)?",
"How many friends were there in Friends?",
"How many rings does Saturn have (major ones)?",
"How many moons does Saturn have (known 2025)?",
"How many bones in a shark’s body?",
"How many senses do humans have (traditional)?",
"How many senses do some scientists say we have?",
"How many colors can the human eye distinguish?",
"How many taste buds does the average tongue have?",
"How many muscles in the human body (approx)?",
"How many cells in the human body (approx)?",
"How many stars in the Milky Way (estimate)?",
"How many galaxies in the observable universe (estimate)?",
"How many atoms in the observable universe (estimate)?",
"How many seconds in a day?",
"How many minutes in a year?",
"How many days until Christmas 2025 from today?",
"How many days has a person aged 30 lived (non-leap)?",
"How many times does the average person blink in a lifetime?",
"How many breaths does the average person take in a day?",
"How many dreams does the average person have per night?",
"How many thoughts does the average person have per day?",
"How many times does your heart beat in a lifetime?",
"How many steps does the average person take in a lifetime?",
"How many words has Shakespeare invented (approx)?",
"How many words are in the English language (2025 estimate)?",
"How many words does the average person know?",
"How many words does the average toddler know at age 2?",
"How many words does the average 4-year-old say per hour?",
"How many questions have you answered in this list?",
"Wait… are we still going?",
"Yes. Yes we are.",
"Final question: are you still reading?",
"Good. You win nothing but my respect."
]
